dist: bionic
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
  - sudo apt-get install -qfy autoconf autotools-dev flex libicu-dev libpcre3-dev libxml2-dev libxml2-utils lttoolbox-dev pkg-config python3-dev python3-lxml python3-setuptools swig unzip xsltproc zip zipcmp
script:
  - autoreconf -fvi
  - ./configure --enable-python-bindings
  - make -j2
  - make test V=1 VERBOSE=1
